version: '3.8'
services:

  spark_master:
    image: spark_master
    ports:
     - 4040:8080
     - 7077:7077
    volumes:
     - shared-pyspark-workspace:./opt/shared_workspace
    networks:
      - local_network

  spark_worker_1:
    image: spark_worker
    ports:
     - 4041:8081
    volumes:
     - shared-pyspark-workspace:./opt/shared_workspace
    networks:
      - local_network

  spark_worker_2:
    image: spark_worker
    ports:
     - 4041:8081
    volumes:
     - shared-pyspark-workspace:./opt/shared_workspace
    networks:
      - local_network


  mongo_db1: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data1:/data/db
    networks:
      - local_network

  mongo_db2: 
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo-data2:/data/db
    networks:
      - local_network

  mongo_db3: 
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - mongo-data3:/data/db
    networks:
      - local_network
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    networks:
      - local_network
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: 
      - 29092:29092
      - 29093:29093
    volumes:
      - kafka_volume:/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL_SAME_HOST://:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 180000
    restart: always
    networks:
      - local_network
    depends_on:
      - zookeeper

networks:
  local_network:

volumes:
  shared-pyspark-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  mongo-data1:
  mongo-data2:
  mongo-data3:
  kafka_volume: